version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  sso-server:
    build: ./sso-server
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - REDIS_URL=redis://redis:6379
      - CLIENT_DOMAIN=http://localhost:3000
      - NODE_ENV=development
    volumes:
      - ./sso-server:/app
      - /app/node_modules
    restart: unless-stopped

  calculator-app:
    build: ./calculator-app
    ports:
      - "3001:80"
    environment:
      - REACT_APP_SSO_SERVER_URL=http://localhost:4000
    volumes:
      - ./calculator-app/src:/app/src
      - ./calculator-app/public:/app/public
    depends_on:
      - sso-server

  notes-app:
    build: ./notes-app
    ports:
      - "3002:80"
    environment:
      - REACT_APP_SSO_SERVER_URL=http://localhost:4000
    volumes:
      - ./notes-app/src:/app/src
      - ./notes-app/public:/app/public
    depends_on:
      - sso-server

volumes:
  redis-data:
